// STEP 1 GO TO JENKINS.IO WEBSIE AND DOWNLOAD JENKINS .WAR FILE
jenkins.io

// STEP 2 MOVE THE WAR TO A JENKINS FOLDER
cd c:\jenkins

//STEP 3 RUN THE JENKINS.WAR FILE
java -jar jenkins.war --httpPort=7076

// STEP 4 SETUP NEW USER ACCOUNT AND LOGIN TO THE DASHBOARD 

