version: '3'
services:
  jenkins:
    container_name: old-jenkins
    image: jenkins/jenkins:2.319.2-lts
    ports:
      - "8081:8080"
    volumes:
      - "$HOME/jenkins_home_old:/var/jenkins_home"
    networks:
      - net2
networks:
  net2: